### ISSUE TITLE
license?

### ISSUE THREAD

**Issue by LifeCANvs** [pisaiah/Vide#12]
Hi. I see that you invite / encourage devs to contribute, but no license is specified for this project...?

Edit: I see now there is a small "license MIT" tag/ badge in the readme. A license file and/or explicit inclusion of license information in the source files would definitely be better :)

**Comment by pisaiah** [comment]
done in https://github.com/pisaiah/Vide/commit/4d292f49df390644afe90704be7900af56b3b1f9
