### ISSUE TITLE
Vide crashes when minimized

### ISSUE THREAD

**Issue by iluuko** [pisaiah/Vide#8]
OS: Windows 10 Pro 64 Bit
Vide Version: 0.0.14
V Version: 0.3.3

Literally just stops working when minimized

**Comment by Utoog** [comment]
Error promt:
Assertion failed: glGetError() == 0, file C:\hostedtoolcache\windows\v\0.3.3\x64\thirdparty\sokol/sokol_gfx.h, line 7664

**Comment by pisaiah** [comment]
fixed
